import { Suspense } from 'react'
import Loading from '@/app/dashboard/loading' 
import Link from 'next/link'

export default function Posts() {

  setTimeout(() => {console.log(222222)}, 7000)

  return (
    <section>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      dashboard
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
    </section>
  )
}