import { Inter } from 'next/font/google'
import './globals.css'
import { ReduxProvider } from "@/store";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
            <h1>我是全局layout</h1>
            <br></br>
            {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
